name: release EFCore

on:
  release:
    types: [published]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Run all tests
      working-directory: ./src/
      run: dotnet test ODatalizer.EFCore.sln
    - name: Replace version
      working-directory: ./src/ODatalizer.EFCore
      shell: bash
      run: |
        sed -i -e "s|<Version>1.0.0</Version>|<Version>${{ github.event.release.tag_name }}</Version>|g" ./ODatalizer.EFCore.csproj
        cat ./ODatalizer.EFCore.csproj
    - name: Build release
      working-directory: ./src/ODatalizer.EFCore
      run: dotnet pack -c Release
    - name: Publish to NuGet.org
      working-directory: ./src/ODatalizer.EFCore/bin/Release
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}