name: test EFCore

on: 
  push:
    branches: 
      - '**'
    tags-ignore:
      - '*.*'
    paths:
      - 'src/ODatalizer/**'
      - 'src/ODatalizer.EFCore/**'
      - 'src/ODatalizer.EFCore.Tests/**'
      - 'src/ODatalizer.EFCore.sln'
      - '.github/workflows/test_efcore.yml'
  pull_request:
    branches: 
      - '**'
    tags-ignore:
      - '*.*'
    paths:
      - 'src/ODatalizer/**'
      - 'src/ODatalizer.EFCore/**'
      - 'src/ODatalizer.EFCore.Tests/**'
      - 'src/ODatalizer.EFCore.sln'

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
      with:
        dotnet-version: 10.0.x
    - name: Clean
      working-directory: ./src/
      run: dotnet clean ODatalizer.EFCore.sln --configuration Release && dotnet nuget locals all --clear
    - name: Run all tests
      working-directory: ./src/
      run: dotnet test ODatalizer.EFCore.sln
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
      with:
        dotnet-version: 10.0.x
    - name: Run all tests
      working-directory: ./src/
      run: dotnet test ODatalizer.EFCore.sln
