name: test

on: 
  push:
    paths:
      - 'src/**'
      - '.github/workflows/test.yml'
    tags-ignore: '*'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/test.yml'
    tags-ignore: '*'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Run all tests
      working-directory: ./src/
      run: dotnet test ODatalizer.EFCore.sln
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Run all tests
      working-directory: ./src/
      run: dotnet test ODatalizer.EFCore.sln
